Upgrade each and every app dependencies. Upgrade gitlab-ci configuration

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,57 +1,118 @@
 stages:
-  - Tests
-  - Build
-  - Release
+  - prepare
+  - tests
+  - build
+  - cleanup
 
 variables:
-  CONTAINER_IMAGE: "registry.ely.by/elyby/skins-renderer-service"
+  PHP_BUILD_IMAGE: edbizarro/gitlab-ci-pipeline-php:7.3-alpine
+  DOCKER_BUILD_IMAGE: docker:19.03.2
+
+  APP_IMAGE_NAME: "$CI_REGISTRY_IMAGE"
+
+#######################
+# Shared script steps #
+#######################
+
+# GitLab do not supports bash syntax in the "variables" definitions,
+# so we use custom step to define all necessary environment variables
+.defineVars: &defineVars |-
+  export VERSION="${CI_COMMIT_TAG:-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}}"
+
+  export APP_VERSIONED_IMAGE_NAME="$APP_IMAGE_NAME:$VERSION"
+  export APP_LATEST_IMAGE_NAME="$APP_IMAGE_NAME:latest"
+
+.dockerLogin: &dockerLogin |-
+  docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
+
+###################
+# Steps to extend #
+###################
+
+.vendorCache:
+  cache:
+    key: backend-deps
+    paths:
+      - vendor
+    policy: pull
+
+#################
+# Prepare stage #
+#################
+
+Precache dependencies:
+  stage: prepare
+  image: $PHP_BUILD_IMAGE
+  extends:
+    - .vendorCache
+  cache:
+    policy: pull-push
+  script:
+    - composer install --ignore-platform-reqs
+
+#################
+# Testing stage #
+#################
 
 PHP-CS-Fixer:
-  image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine
-  stage: Tests
+  stage: tests
+  image: $PHP_BUILD_IMAGE
   cache:
     key: vendor
     paths:
       - vendor
-  before_script:
-    - composer install --ignore-platform-reqs
   script:
     - vendor/bin/php-cs-fixer fix -v --dry-run
 
 PHPUnit:
-  image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine
-  stage: Tests
-  cache:
-    key: vendor
-    paths:
-      - vendor
-  before_script:
-    - composer install --ignore-platform-reqs
+  stage: tests
+  image: $PHP_BUILD_IMAGE
+  extends:
+    - .vendorCache
   script:
     - vendor/bin/phpunit --coverage-text
 
+###############
+# Build stage #
+###############
 
-Build Docker image:
-  image: docker:18.02
-  stage: Build
+Docker:
+  stage: build
+  image: $DOCKER_BUILD_IMAGE
   before_script:
-    - docker login -u gitlab-ci -p $CI_BUILD_TOKEN registry.ely.by
+    - *defineVars
+    - *dockerLogin
   script:
-    - export IMAGE_NAME="$CONTAINER_IMAGE:latest"
-    - docker build --pull --build-arg "build_env=prod" -t $IMAGE_NAME .
+    # Download previous image to use it as a cache
+    - docker pull "$APP_LATEST_IMAGE_NAME" || true
+    # Build image
+    - >
+      docker build
+      --pull
+      --cache-from "$APP_LATEST_IMAGE_NAME"
+      -t "$APP_VERSIONED_IMAGE_NAME"
+      -t "$APP_LATEST_IMAGE_NAME" .
+    # Push images to the registry
+    - docker push $APP_VERSIONED_IMAGE_NAME
+    - docker push $APP_LATEST_IMAGE_NAME
   only:
     - master
     - tags
 
-Release :latest tag:
-  image: docker:18.02
-  stage: Release
+#################
+# Cleanup stage #
+#################
+
+Remove Docker images:
+  stage: cleanup
+  image: $DOCKER_BUILD_IMAGE
   variables:
     GIT_STRATEGY: none
   before_script:
-    - docker login -u gitlab-ci -p $CI_BUILD_TOKEN registry.ely.by
+    - *defineVars
   script:
-    - docker push $CONTAINER_IMAGE:latest
+    - docker rmi "$APP_LATEST_IMAGE_NAME" "$APP_VERSIONED_IMAGE_NAME" || true
+  when: always
   only:
     - master
     - tags
